<?php

namespace Tests\Unit\Repository;

use App\Models\Genre;
use App\Repository\Eloquent\BaseRepository;
use App\Repository\Eloquent\GenreRepository;
use App\Repository\Interfaces\GenreRepositoryInterface;
use App\Repository\Interfaces\EloquentRepositoryInterface;
use PHPUnit\Framework\TestCase;

class GenreRepositoryTest extends TestCase
{
    /**
     * @var GenreRepository
     */
    private $genreRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->genreRepository = new GenreRepository(new Genre());
    }


    public function testInterfaces()
    {
        $expected_interfaces = [EloquentRepositoryInterface::class, GenreRepositoryInterface::class];
        $interfaces = class_implements($this->genreRepository);
        $genreRepositoryInterfaces = array_values($interfaces);
        $this->assertEqualsCanonicalizing($expected_interfaces, $genreRepositoryInterfaces);
    }

    public function testParents(){
        $expected_parents = [BaseRepository::class];
        $parents = class_parents($this->genreRepository);
        $genreRepositoryParents = array_values($parents);
        $this->assertEqualsCanonicalizing($expected_parents, $genreRepositoryParents);
    }
}
