<?php

namespace Tests\Unit\Http\Requests\Category\v1;

use App\Http\Requests\BaseRequest;
use App\Http\Requests\Category\Interfaces\CategoryStoreRequestInterface;
use App\Http\Requests\Category\v1\CategoryBaseRequest;
use App\Http\Requests\Category\v1\CategoryStoreRequest;
use Symfony\Component\HttpFoundation\Request as FoundationRequest;
use ArrayAccess;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Request;
use Tests\TestCase;
use Illuminate\Contracts\Validation\ValidatesWhenResolved;

/**
 * @group requests
 * @group category
 */
class CategoryStoreRequestTest extends TestCase
{
    private $categoryRequest;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->categoryRequest = new CategoryStoreRequest([]);
    }

    public function testInterfaces()
    {
        $expected_interfaces = [CategoryStoreRequestInterface::class, ArrayAccess::class, Arrayable::class, ValidatesWhenResolved::class];
        $interfaces = class_implements($this->categoryRequest);
        $categoryRequestInterfaces = array_values($interfaces);
        $this->assertEqualsCanonicalizing($expected_interfaces, $categoryRequestInterfaces);
    }

    public function testParents()
    {
        $expected_parents = [CategoryBaseRequest::class, BaseRequest::class, FormRequest::class, Request::class, FoundationRequest::class];
        $parents = class_parents($this->categoryRequest);
        $categoryRequestParents = array_values($parents);
        $this->assertEqualsCanonicalizing($expected_parents, $categoryRequestParents);
    }
}
