<?php

namespace Tests\Feature\Repository;

use App\Models\Genre;
use App\Repository\Eloquent\GenreRepository;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Str;
use Tests\TestCase;
/**
 * @group repository
 * @group genre
 */
class GenreRepositoryTest extends TestCase
{
    use DatabaseMigrations;

    /**
     * @var Genre
     */
    private $genre;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->genre = new GenreRepository(new Genre());
    }

    public function testList()
    {
        factory(Genre::class, 10)->create();
        $genres = $this->genre->all();
        self::assertCount(10, $genres);
        $expected_genre_keys = ['id', 'name', 'is_active', 'created_at', 'updated_at', 'deleted_at'];
        $genre_keys = array_keys($genres->first()->getAttributes());
        self::assertEqualsCanonicalizing($expected_genre_keys, $genre_keys);
    }

    public function testCreate()
    {
        $cat = $this->genre->create(['name' => 'Teste 1']);
        self::assertEquals('Teste 1', $cat->name);
        $cat->refresh();
        self::assertEquals('Teste 1', $cat->name);
        $isUUID = preg_match('/[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i', $cat->id);
        self::assertEquals(1, $isUUID);
        self::assertTrue($cat->is_active);
        $cat_1 = $this->genre->create(['name' => 'Teste 2', ]);
        $cat_1->refresh();
        self::assertEquals('Teste 2', $cat_1->name);
        self::assertTrue($cat_1->is_active);
        $cat_2 = $this->genre->create(['name' => 'Teste 3',  'is_active' => true]);
        $cat_2->refresh();
        self::assertEquals('Teste 3', $cat_2->name);
        self::assertTrue($cat_2->is_active);
        $cat_3 = $this->genre->create(['name' => 'Teste 4', 'is_active' => false]);
        $cat_3->refresh();
        self::assertEquals('Teste 4', $cat_3->name);
        self::assertFalse($cat_3->is_active);
        $cat_4 = $this->genre->create(['name' => 'Teste 5', 'is_active' => false]);
        $cat_4->refresh();
        self::assertEquals('Teste 5', $cat_4->name);
        self::assertFalse($cat_4->is_active);
        $cat_5 = $this->genre->create(['name' => 'Teste 6',  'is_active' => false]);
        $cat_5->refresh();
        self::assertEquals('Teste 6', $cat_5->name);
        //@todo make sure empty strig return null
        self::assertFalse($cat_5->is_active);
    }

    public function testUpdate()
    {
        $genre = factory(Genre::class)->create();
        $genre->update(['name' => 'Teste 1', 'is_active' => false]);
        self::assertEquals('Teste 1', $genre->name);
        self::assertFalse($genre->is_active);
        $genre_2 = factory(Genre::class)->create();
        $genre_2->update(['is_active' => false]);
        self::assertFalse($genre_2->is_active);
        $genre_3 = factory(Genre::class)->create();
        $genre_3->update(['name' => 'Teste 3']);
        self::assertEquals('Teste 3', $genre_3->name);
    }

    public function testDelete()
    {
        $genre = factory(Genre::class)->create();
        self::assertCount(1, $this->genre->all());
        self::assertTrue($genre->delete());
        self::assertCount(0, $this->genre->all());
        self::assertCount(1, $this->genre->getTrashed());
    }

    public function testFindFail()
    {
        $this->expectException(ModelNotFoundException::class);
        $this->genre->find(Str::uuid());
    }
    public function testFind()
    {
        $uuid = Str::uuid();
        factory(Genre::class)->create(['id' => $uuid, 'name' => 'Teste 1']);
        $genre = $this->genre->find($uuid);
        self::assertInstanceOf(Genre::class, $genre);
    }
}
