<?php

namespace Tests\Feature\Http\Requests\Category\v1;

use App\Http\Requests\Category\v1\CategoryBaseRequest;
use App\Http\Requests\Category\v1\CategoryStoreRequest;
use Faker\Factory;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Validator;
use Tests\TestCase;
use Faker\Factory as FakerFactory;
use Illuminate\Routing\Redirector;
use Illuminate\Validation\ValidationException;
use function app;

/**
 * @group requests
 * @group category
 */
class CategoryStoreRequestTest extends TestCase
{

    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_CategoryStoreRequest_empty()
    {
        try {
            $request = new CategoryStoreRequest([]);
            $request
                ->setContainer(app())
                ->setRedirector(app(Redirector::class))
                ->validateResolved();
        } catch (ValidationException $ex) {
            print_r($ex->errors(), true);
        }
        //\Log::debug(print_r($ex->errors(), true));
        self::assertTrue(isset($ex));
        self::assertArrayHasKey('name', $ex->errors());
    }


    public function test_CategoryStoreRequest_success()
    {
        $faker = FakerFactory::create();
        $param = [
            'name' => $faker->colorName,
            'description' => $faker->text,
            'is_active' => $faker->boolean,
        ];
        try {
            $request = new CategoryStoreRequest($param);
            $request
                ->setContainer(app())
                ->setRedirector(app(Redirector::class))
                ->validateResolved();
        } catch (ValidationException $ex) {
        }

        $this->assertFalse(isset($ex));
    }

    /**
     * @dataProvider provideValidData
     */
    public function testValidData(array $data)
    {
        $request = new CategoryStoreRequest();

        $validator = Validator::make($data, $request->rules());

        $this->assertTrue($validator->passes());
    }

    public function provideValidData()
    {
        $faker = \Faker\Factory::create(Factory::DEFAULT_LOCALE);

        return [
            [[
                'name' => 'test',
                'description' => 'this is a test'
            ]],
            [[
                'name' => $faker->colorName,
                'description' => $faker->text,
                'is_active' => $faker->boolean,
            ]],
            [[
                'name' => $faker->colorName,
                'description' => null,
                'is_active' => $faker->boolean,
            ]]
            // ...
        ];
    }
    /**
     * @dataProvider provideInvalidData
     */
    public function testInvalidData(array $data)
    {
        $request = new CategoryStoreRequest();

        $validator = Validator::make($data, $request->rules());


        $this->assertFalse($validator->passes());
    }

    public function provideInvalidData()
    {
        $faker = \Faker\Factory::create(Factory::DEFAULT_LOCALE);
        return [
            [[]], // missing fields
            [[
                'title' => 'test' // missing body
            ]],
            [[
                'description' => $faker->text,
                'is_active' => $faker->boolean, // missing name
            ]],
            [[
                'name' => str_repeat('a', CategoryBaseRequest::NAME_MAX_LENGTH + 1), // title too long
                'description' => $faker->text,
            ]],
            [[
                'name' => $faker->colorName,
                'description' => $faker->text,
                'is_active' => 'true',
            ]],
            [[
                'name' => $faker->colorName,
                'description' => $faker->text,
                'is_active' => 'false',
            ]]
            // ...
        ];
    }
}
