<?php

namespace Tests\Unit\Services;

use App\Models\Category;
use App\Repository\Eloquent\CategoryRepository;
use App\Services\CategoryService;
use App\Services\Interfaces\CategoryServiceInterface;
use PHPUnit\Framework\TestCase;
/**
 * @group service
 * @group category
 */
class CategoryServiceTest extends TestCase
{
    /**
     * @var CategoryService
     */
    private $categoryService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->categoryService = new CategoryService(new CategoryRepository(new Category()));
    }


    public function testInterfaces()
    {
        $expected_interfaces = [CategoryServiceInterface::class];
        $interfaces = class_implements($this->categoryService);
        $categoryService = array_values($interfaces);
        $this->assertEqualsCanonicalizing($expected_interfaces, $categoryService);
    }

}
