<?php

namespace Tests\Unit\Services;

use App\Models\Genre;
use App\Repository\Eloquent\GenreRepository;
use App\Services\GenreService;
use App\Services\Interfaces\GenreServiceInterface;
use PHPUnit\Framework\TestCase;

class GenreServiceTest extends TestCase
{
    /**
     * @var GenreService
     */
    private $genreService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->genreService = new GenreService(new GenreRepository(new Genre()));
    }


    public function testInterfaces()
    {
        $expected_interfaces = [GenreServiceInterface::class];
        $interfaces = class_implements($this->genreService);
        $genreService = array_values($interfaces);
        $this->assertEqualsCanonicalizing($expected_interfaces, $genreService);
    }
}
